import type { AlbumDetails } from '../albumDetails';

export function createMockAlbumDetails(overrides: Partial<AlbumDetails> = {}): AlbumDetails {
  return {
    albumId: 'test-album',
    slug: 'test-album',
    title: 'Test Album',
    cover: 'cover',
    userId: 'user-1',
    dbAlbumId: 'uuid-1',
    description: 'Test Description',
    details: [],
    release: { date: '2024-01-01' },
    artwork: {
      photographer: '',
      photographerURL: '',
      designer: '',
      designerURL: '',
    },
    purchase: {
      allowDownloadSale: '',
      regularPrice: '0.99',
      currency: 'RUB',
    },
    serviceButtons: {},
    visibility: { isPublished: true, isPublic: true },
    tracks: [
      {
        id: '1',
        title: 'Track 1',
        orderIndex: 0,
        duration: 180,
        src: 'track1.mp3',
        playbackLocked: false,
        visibility: 'public',
        stemsAvailability: 'hidden',
        audioContainer: null,
        audioCodec: null,
        audioBitrate: null,
        audioSampleRate: null,
        audioBitDepth: null,
        audioChannels: null,
        audioDuration: null,
        audioFileSize: null,
      },
      {
        id: '2',
        title: 'Track 2',
        orderIndex: 1,
        duration: 200,
        src: 'track2.mp3',
        playbackLocked: false,
        visibility: 'public',
        stemsAvailability: 'hidden',
        audioContainer: null,
        audioCodec: null,
        audioBitrate: null,
        audioSampleRate: null,
        audioBitDepth: null,
        audioChannels: null,
        audioDuration: null,
        audioFileSize: null,
      },
    ],
    ...overrides,
  };
}
