/** Shared auto-dismiss durations for dashboard and feature toasts (ms). */
export const MIX_TOAST_DURATION_MS = 4000;
export const STEM_ADDED_TOAST_DURATION_MS = 4000;
export const STEM_DELETED_TOAST_DURATION_MS = 4000;
export const PURCHASE_REMOVED_TOAST_DURATION_MS = 4000;
export const ARCHIVE_ARTIST_REMOVED_TOAST_DURATION_MS = 4000;
export const ALBUM_DELETED_TOAST_DURATION_MS = 4000;
export const TRACK_DELETED_TOAST_DURATION_MS = 4000;
export const ARTICLE_DELETED_TOAST_DURATION_MS = 4000;
export const ALBUM_PUBLISHED_TOAST_DURATION_MS = 4500;
export const ALBUM_CREATED_TOAST_DURATION_MS = 4500;
export const TRACKS_UPLOADED_TOAST_DURATION_MS = 4500;
export const LYRICS_SYNC_SAVED_TOAST_DURATION_MS = 4500;
export const LYRICS_SYNC_REMOVED_TOAST_DURATION_MS = 4500;
export const DASHBOARD_ERROR_TOAST_DURATION_MS = 4500;
export const ARTICLE_EDITOR_TOAST_DURATION_MS = 4500;
export const ARTICLE_EDITOR_TOAST_WITH_ACTION_DURATION_MS = 6500;
export const ALBUM_PURCHASE_SUCCESS_TOAST_DURATION_MS = 4500;
