/**
 * Writes dist/_redirects for production/deploy-preview from netlify.toml API rules.
 *
 * Netlify evaluates _redirects before netlify.toml (first match wins), so production
 * must ship the full /api/* routing table here — not only a :splat catch-all.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

interface RedirectRule {
  from: string;
  to: string;
  status: number;
  force: boolean;
}

function parseApiRedirectsFromNetlifyToml(content: string): RedirectRule[] {
  const rules: RedirectRule[] = [];

  for (const block of content.split('[[redirects]]').slice(1)) {
    const from = block.match(/^\s*from\s*=\s*"([^"]+)"/m)?.[1];
    const to = block.match(/^\s*to\s*=\s*"([^"]+)"/m)?.[1];
    if (!from?.startsWith('/api/') || !to) continue;

    rules.push({
      from,
      to,
      status: Number(block.match(/^\s*status\s*=\s*(\d+)/m)?.[1] ?? 200),
      force: /^\s*force\s*=\s*true/m.test(block),
    });
  }

  return rules;
}

function toRedirectsLine(rule: RedirectRule): string {
  const status = rule.force ? `${rule.status}!` : String(rule.status);
  return `${rule.from}  ${rule.to}  ${status}`;
}

const root = resolve(__dirname, '..');
const distDir = resolve(root, 'dist');
const apiRules = parseApiRedirectsFromNetlifyToml(
  readFileSync(resolve(root, 'netlify.toml'), 'utf8')
);

if (apiRules.length === 0) {
  throw new Error('No /api/* redirects found in netlify.toml');
}

mkdirSync(distDir, { recursive: true });

const lines = [
  '# Generated by scripts/generate-dist-redirects.ts — do not edit by hand.',
  '# Netlify processes _redirects before netlify.toml; first match wins.',
  '# See: https://docs.netlify.com/manage/routing/redirects/overview/#rule-processing-order',
  '',
  ...apiRules.map(toRedirectsLine),
  '/*      /index.html                 200',
  '',
];

writeFileSync(resolve(distDir, '_redirects'), lines.join('\n'), 'utf8');
console.log(`✅ dist/_redirects: ${apiRules.length} API rules + SPA fallback`);
