/**
 * Writes dist/_redirects for production/deploy-preview from netlify.toml API rules.
 *
 * Netlify evaluates _redirects before netlify.toml (first match wins), so production
 * must ship the full /api/* routing table here — not only a :splat catch-all.
 *
 * Do not keep this file locally during Netlify Dev — see scripts/remove-dist-redirects-for-dev.ts.
 */

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { resolve } from 'node:path';

interface RedirectRule {
  from: string;
  to: string;
  status: number;
  force: boolean;
}

function parseApiRedirectsFromNetlifyToml(content: string): RedirectRule[] {
  const rules: RedirectRule[] = [];

  for (const block of content.split('[[redirects]]').slice(1)) {
    const from = block.match(/^\s*from\s*=\s*"([^"]+)"/m)?.[1];
    const to = block.match(/^\s*to\s*=\s*"([^"]+)"/m)?.[1];
    if (!from?.startsWith('/api/') || !to) continue;

    rules.push({
      from,
      to,
      status: Number(block.match(/^\s*status\s*=\s*(\d+)/m)?.[1] ?? 200),
      force: /^\s*force\s*=\s*true/m.test(block),
    });
  }

  return rules;
}

function toRedirectsLine(rule: RedirectRule): string {
  const status = rule.force ? `${rule.status}!` : String(rule.status);
  return `${rule.from}  ${rule.to}  ${status}`;
}

const root = resolve(__dirname, '..');
const distDir = resolve(root, 'dist');
const documentBundleDir = resolve(root, 'netlify/functions/_document');
const source404Html = resolve(documentBundleDir, '404.html');
const apiRules = parseApiRedirectsFromNetlifyToml(
  readFileSync(resolve(root, 'netlify.toml'), 'utf8')
);

if (apiRules.length === 0) {
  throw new Error('No /api/* redirects found in netlify.toml');
}

mkdirSync(distDir, { recursive: true });
mkdirSync(documentBundleDir, { recursive: true });

const indexHtmlPath = resolve(distDir, 'index.html');
copyFileSync(indexHtmlPath, resolve(documentBundleDir, 'index.html'));

if (!readFileSync(source404Html, 'utf8').includes('noindex')) {
  throw new Error('netlify/functions/_document/404.html must include noindex robots meta');
}

const lines = [
  '# Generated by scripts/generate-dist-redirects.ts — do not edit by hand.',
  '# Netlify processes _redirects before netlify.toml; first match wins.',
  '# See: https://docs.netlify.com/manage/routing/redirects/overview/#rule-processing-order',
  '',
  '/sitemap.xml  /.netlify/functions/sitemap  200!',
  ...apiRules.map(toRedirectsLine),
  '/*      /.netlify/functions/public-document  200',
  '',
];

writeFileSync(resolve(distDir, '_redirects'), lines.join('\n'), 'utf8');
console.log(
  `✅ dist/_redirects: ${apiRules.length} API rules + public-document gate; bundled index.html for function`
);
